# Generated by Django 4.1.1 on 2022-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user.default.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
