# Generated by Django 4.1.1 on 2022-11-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user_default.png', null=True, upload_to='profiles/'),
        ),
    ]
